name: Integration Continue

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  backend-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    services:
      mysql:
        image: mysql:8
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.CI_DB_PASSWORD }}
          MYSQL_DATABASE: code_lingoenv:
          DATABASE_URL: mysql://sahrane:${{ secrets.CI_DB_PASSWORD }}@localhost:3306/code_lingo



    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20.9.0"

      - name: Installation des dépendances
        run: npm install

      - name: Exécution des tests d'intégration
        run: npm test
        env:
          MYSQL_HOST: localhost
          MYSQL_USER: root
          MYSQL_PASSWORD: ${{ secrets.CI_DB_PASSWORD }}
          MYSQL_DB: code_lingo
